version: '3'

services:
  postgres_db:
    image: postgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/ # persist data even if container shuts down
    restart: always
    environment:
      POSTGRES_DB: wordpress
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: wordpress

  # TODO: needs replacing with a PHP image so that we can change the DB Driver to Postgres
  wordpress:
    depends_on:
      - db
    image: wordpress:5.6.0-php7.3-apache
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - ./public/wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  postgres_db_data: # named volumes can be managed easier using docker-compose